spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.41.165.41:3306/houseSchool?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    open: true
    database: 0
    password:
    host: 121.41.165.41
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.gxa.modules.*.entity

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 1

#存储配置
storage:
  config:
    type: 6 # 特别特别重要，决定使用说明方式进行上传 1：七牛  2：阿里云  3：腾讯云   4：FastDFS   5：本地上传    6：minio
    qiniuDomain: http://7xqbwh.dl1.z0.glb.clouddn.com #七牛绑定的域名
    qiniuPrefix: upload #七牛路径前缀
    qiniuAccessKey:  #七牛ACCESS_KEY
    qiniuSecretKey: uIwJHevMRWU0VLxFvgy0tAcOdGqasdtVlJkdy6vV #七牛SECRET_KEY
    qiniuBucketName: #七牛存储空间名

    aliyunDomain: imagejzy.oss-cn-chengdu.aliyuncs.com #阿里云绑定的域名
    aliyunPrefix: img #阿里云路径前缀
    aliyunEndPoint: oss-cn-chengdu.aliyuncs.com #阿里云EndPoint
    aliyunAccessKeyId: LTAI5tLuRNZtbDNTdWW46hbc #阿里云AccessKeyId
    aliyunAccessKeySecret: AbPL60HrN2lheRodVK0Ve0yTSaeY2L #阿里云AccessKeySecret
    aliyunBucketName: imagejzy #阿里云BucketName


    tcloudDomain: #腾讯云绑定的域名
    tcloudPrefix: #腾讯云路径前缀
    tcloudAppId: #腾讯云AppId
    tcloudSecretId: #腾讯云SecretId
    tcloudSecretKey: #腾讯云SecretKey
    tcloudBucketName: #腾讯云BucketName
    tcloudRegion: #腾讯云COS所属地区

    fastdfsDomain: #FastDFS绑定的域名

    localDomain: #本地上传绑定的域名
    localPrefix: #本地上传路径前缀
    localPath: #本地上传存储目录

    minioEndPoint: http://121.41.165.41:9000 #Minio EndPoint
    minioAccessKey: 88PCGLJI3AURHR5RCK0Q #accessKey
    minioSecretKey: 9kkr6crbxOze6BUS6pApjNPh9lCIMpZstgUnGHOk #secretKey
    minioBucketName: files #BucketName
    minioPrefix: houseSchool #MinIO上传路径前缀

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.10:22122


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql